model:
  work_space: "./"
  name: FNO3D_time
  in_channels: 10
  out_channels: 1
  input_resolution: 64
  modes: 8
  width: 20
  depth: 4
  output_timestep: 40
  input_timestep: 10
  sub: 1
data:
  name: "navier_stoke_3d"
  path: "./dataset"
  batch_size: 10
  resolution: 64
optimizer:
  initial_lr: 0.01
  warmup_epochs: 1
  train_epochs: 150
  weight_decay: 0.0001

summary_dir: "./summary"
eval_interval: 10
save_ckpt_interval: 50
test_batch_size: 1