# case burgers
geometry:
  coord_dim: 1
  time_dim: 1
  coord_min: -1.0
  coord_max: 1.0
  time_min: 0.0
  time_max: 1.0
model:
  name: MLP_with_Residual
  in_channels: 2
  out_channels: 1
  activation: "tanh"
  layers: 5
  neurons: 20
  residual: false
amp_level: O3
data:
  domain:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  BC:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  IC:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  time:
    size: 8192
    random_sampling: true
    sampler: "uniform"
optimizer:
  initial_lr: 0.001
  warmup_epochs: 1
  weight_decay: 0.0
  gamma: 0.1
  milestones: [2000, 4000]
cmaes:
  popsize: 20
  std: 0.5
mgda:
  norm_type: "l2" # other choice l2/loss/loss+/none
  ratio: 0.6
train_batch_size: 8192
test_batch_size: 8192
train_data_path: "/home/LAB/liulin/NRE/dataset"
test_data_path: "/home/LAB/liulin/NRE/dataset"
train_epochs: 100
eval_interval_epochs: 10
save_checkpoint_epochs: 50
visual_resolution: 100  
keep_checkpoint_max: 10
train_with_eval: true
load_ckpt: false
save_ckpt: true
save_ckpt_path: "./ckpt"
summary_dir: "./summary"
visual_dir: "./vision"
