# case periodic hill
model:
  in_channels: 2
  out_channels: 6
  activation: "tanh"
  layers: 5
  neurons: 64
  residual: false
  amp_level: O3
data:
  domain:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  BC:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  IC:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  time:
    size: 8192
    random_sampling: true
    sampler: "uniform"
  train_batch_size: 1000
  test_batch_size: 20000
  train_data_path: "./dataset"
  test_data_path: "./dataset"
optimizer:
  train_epochs: 160
  initial_lr: 0.001
  warmup_epochs: 1
  weight_decay: 0.0
  gamma: 0.1
  milestones: [2000, 4000]
cmaes:
  popsize: 20
  std: 0.5
mgda:
  norm_type: "l2" # other choice l2/loss/loss+/none
  ratio: 0.1
summary:
  eval_interval_epochs: 10
  save_checkpoint_epochs: 50
  visual_resolution: 100
  keep_checkpoint_max: 10
  train_with_eval: true
  load_ckpt: false
  save_ckpt: true
  save_ckpt_path: "./ckpt"
  summary_dir: "./summary"
  visual_dir: "./vision"
