model_type: fno
model:
    in_channels: 100
    out_channels: 8
    resolution:
        - 64
        - 128
    modes: 12
    channels: 20
    depths: 6
data:
    path: ./data
    num_samples:
        train: 2000
        test: 500
train:
    batch_size: 32
    lr_init: 1.e-4
    epochs: 500
    optimizer: Adam
    weight_decay: 0.0
    lr_scheduler:
        enable_warmup: True
        warmup_epochs: 10
test:
    batch_size: 10
    interval: 50
record_path: ./exp

