model_type: unet
model:
    in_channels: 100
    out_channels: 8
    channels: 20
data:
    path: ./data
    num_samples:
        train: 500
        test: 500
train:
    batch_size: 32
    lr_init: 1.e-4
    epochs: 500
    optimizer: Adam
    weight_decay: 0.0
    lr_scheduler:
        enable_warmup: True
        warmup_epochs: 10
test:
    batch_size: 10
    interval: 50
record_path: ./exp

