unit: 
    'Relative Total Pressure': 'Pt[kPa]'
    'Absolute Total Pressure': 'Pt[kPa]'
    'Static Pressure': 'Ps[kPa]'
    'Static Temperature': 'Ts[K]'
    'Absolute Total Temperature': 'Tt[K]'
    'Vx': 'Vx[m/s]'
    'Vy': 'Vy[m/s]'
    'Vz': 'Vz[m/s]'
    'Density': r'$\mathrm{\rho[kg/m^{3}]}$'

