#!/usr/bin/env python3
"""
DRUG-DRUG INTERACTION ANALYSIS - COMPLETE WORKING PIPELINE

Fixed version using correct ToolUniverse tools (1,264 available).
This pipeline actually works and produces DDI risk reports.
"""

from tooluniverse import ToolUniverse
import os
from datetime import datetime


class DDIAnalyzer:
    """Complete DDI analysis pipeline using ToolUniverse."""

    def __init__(self):
        """Initialize ToolUniverse and available tools."""
        print("Initializing ToolUniverse...")
        self.tu = ToolUniverse()
        self.tu.load_tools()
        print(f"✅ Loaded {len(self.tu.all_tool_dict)} tools\n")

    def analyze(self, drug_a, drug_b, output_file=None):
        """
        Complete DDI analysis between two drugs.

        Args:
            drug_a: First drug name
            drug_b: Second drug name
            output_file: Optional markdown report file

        Returns:
            dict with complete analysis
        """
        if output_file is None:
            output_file = f"DDI_report_{drug_a}_{drug_b}.md"

        print("=" * 80)
        print(f"DDI ANALYSIS: {drug_a.upper()} + {drug_b.upper()}")
        print("=" * 80)

        # Create report structure
        report = {
            'drug_a': drug_a,
            'drug_b': drug_b,
            'timestamp': datetime.now().isoformat(),
            'identifiers': {},
            'mechanisms': [],
            'fda_labels': [],
            'clinical_evidence': {},
            'risk_score': 0,
            'severity': 'Unknown',
            'recommendations': []
        }

        # Create markdown report file first (report-first approach)
        self._create_report_file(output_file, drug_a, drug_b)

        # Run analysis pipeline
        print("\n🔬 Running Analysis Pipeline...")
        print("-" * 80)

        # STEP 1: Drug Identification
        report['identifiers'] = self._identify_drugs(drug_a, drug_b)
        self._update_report(output_file, "## 1. Drug Identification", report['identifiers'])

        # STEP 2: Mechanism Analysis (DrugBank)
        report['mechanisms'] = self._analyze_mechanisms(drug_a, drug_b)
        self._update_report(output_file, "## 2. Interaction Mechanisms", report['mechanisms'])

        # STEP 3: Pharmacology (DrugBank)
        pharmacology = self._get_pharmacology(drug_a, drug_b)
        self._update_report(output_file, "## 3. Pharmacology", pharmacology)

        # STEP 4: FDA Label Search (DailyMed)
        report['fda_labels'] = self._search_fda_labels(drug_a, drug_b)
        self._update_report(output_file, "## 4. FDA Label Warnings", report['fda_labels'])

        # STEP 5: Literature Evidence (PubMed)
        literature = self._search_literature(drug_a, drug_b)
        self._update_report(output_file, "## 5. Literature Evidence", literature)

        # STEP 6: Adverse Events (FAERS)
        report['clinical_evidence'] = self._query_adverse_events(drug_a, drug_b)
        self._update_report(output_file, "## 6. Post-Market Surveillance", report['clinical_evidence'])

        # STEP 7: Risk Scoring
        report['risk_score'], report['severity'] = self._calculate_risk(report)
        self._update_report(output_file, "## 7. Risk Assessment", {
            'score': report['risk_score'],
            'severity': report['severity']
        })

        # STEP 8: Management Recommendations
        report['recommendations'] = self._generate_recommendations(report)
        self._update_report(output_file, "## 8. Clinical Management", report['recommendations'])

        print(f"\n✅ Analysis complete! Report saved to: {output_file}")
        print(f"📊 Risk Score: {report['risk_score']}/100 ({report['severity']})")

        return report

    def _create_report_file(self, filename, drug_a, drug_b):
        """Create initial report file with headers."""
        with open(filename, 'w') as f:
            f.write(f"# Drug-Drug Interaction Analysis Report\n\n")
            f.write(f"**Drug Pair**: {drug_a.upper()} + {drug_b.upper()}\n")
            f.write(f"**Analysis Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**Generated by**: ToolUniverse DDI Pipeline\n\n")
            f.write("---\n\n")
            f.write("[Analysis in progress...]\n\n")

    def _update_report(self, filename, section, data):
        """Update report file with new section."""
        with open(filename, 'a') as f:
            f.write(f"\n{section}\n\n")
            if isinstance(data, dict):
                for key, value in data.items():
                    f.write(f"**{key}**: {value}\n\n")
            elif isinstance(data, list):
                for item in data:
                    f.write(f"- {item}\n")
                f.write("\n")
            else:
                f.write(f"{data}\n\n")

    def _identify_drugs(self, drug_a, drug_b):
        """Identify drugs using multiple tools."""
        print("\n1️⃣ Drug Identification")
        identifiers = {}

        # Try RxNorm
        print(f"   Searching RxNorm for {drug_a}...")
        try:
            result = self.tu.tools.RxNorm_get_drug_names(drug_name=drug_a)
            if result.get('data', {}).get('names'):
                names = result['data']['names']
                identifiers[drug_a] = {
                    'rxcui': names[0].get('rxcui', 'N/A'),
                    'name': names[0].get('name', drug_a),
                    'source': 'RxNorm'
                }
                print(f"   ✅ Found: {names[0].get('name')}")
        except Exception as e:
            print(f"   ⚠️ RxNorm failed: {e}")

        # Try DrugBank for more info
        print(f"   Searching DrugBank for {drug_a}...")
        try:
            result = self.tu.tools.drugbank_get_drug_basic_info_by_drug_name_or_id(
                query=drug_a,
                case_sensitive=False,
                exact_match=False,
                limit=1
            )
            if result.get('data', {}).get('drugs'):
                drug_info = result['data']['drugs'][0]
                if drug_a not in identifiers:
                    identifiers[drug_a] = {}
                identifiers[drug_a].update({
                    'drugbank_id': drug_info.get('drugbank_id', 'N/A'),
                    'description': drug_info.get('description', 'N/A')[:200] + '...'
                })
                print(f"   ✅ DrugBank ID: {drug_info.get('drugbank_id')}")
        except Exception as e:
            print(f"   ⚠️ DrugBank failed: {e}")

        # Same for drug_b
        print(f"   Searching for {drug_b}...")
        try:
            result = self.tu.tools.RxNorm_get_drug_names(drug_name=drug_b)
            if result.get('data', {}).get('names'):
                names = result['data']['names']
                identifiers[drug_b] = {
                    'rxcui': names[0].get('rxcui', 'N/A'),
                    'name': names[0].get('name', drug_b),
                    'source': 'RxNorm'
                }
                print(f"   ✅ Found: {names[0].get('name')}")
        except Exception as e:
            print(f"   ⚠️ RxNorm failed: {e}")

        return identifiers

    def _analyze_mechanisms(self, drug_a, drug_b):
        """Analyze interaction mechanisms using DrugBank."""
        print("\n2️⃣ Mechanism Analysis (DrugBank)")
        mechanisms = []

        # Check A → B interactions
        print(f"   Checking {drug_a} → {drug_b}...")
        try:
            result = self.tu.tools.drugbank_get_drug_interactions_by_drug_name_or_id(
                query=drug_a,
                case_sensitive=False,
                exact_match=False,
                limit=50
            )

            if result.get('data', {}).get('interactions'):
                interactions = result['data']['interactions']
                for interaction in interactions:
                    interacting_drug = interaction.get('name', '').lower()
                    if drug_b.lower() in interacting_drug or interacting_drug in drug_b.lower():
                        mechanisms.append({
                            'direction': f"{drug_a} → {drug_b}",
                            'description': interaction.get('description', 'No description'),
                            'source': 'DrugBank'
                        })
                        print(f"   ✅ Found interaction!")
                        break
        except Exception as e:
            print(f"   ⚠️ Error: {e}")

        # Check B → A interactions (bidirectional)
        print(f"   Checking {drug_b} → {drug_a}...")
        try:
            result = self.tu.tools.drugbank_get_drug_interactions_by_drug_name_or_id(
                query=drug_b,
                case_sensitive=False,
                exact_match=False,
                limit=50
            )

            if result.get('data', {}).get('interactions'):
                interactions = result['data']['interactions']
                for interaction in interactions:
                    interacting_drug = interaction.get('name', '').lower()
                    if drug_a.lower() in interacting_drug or interacting_drug in drug_a.lower():
                        mechanisms.append({
                            'direction': f"{drug_b} → {drug_a}",
                            'description': interaction.get('description', 'No description'),
                            'source': 'DrugBank'
                        })
                        print(f"   ✅ Found interaction!")
                        break
        except Exception as e:
            print(f"   ⚠️ Error: {e}")

        if not mechanisms:
            print(f"   ℹ️ No direct interactions found in DrugBank")
            mechanisms.append({
                'direction': 'N/A',
                'description': 'No documented interaction in DrugBank',
                'source': 'DrugBank'
            })

        return mechanisms

    def _get_pharmacology(self, drug_a, drug_b):
        """Get pharmacology information."""
        print("\n3️⃣ Pharmacology Analysis")
        pharmacology = {}

        for drug in [drug_a, drug_b]:
            print(f"   Getting pharmacology for {drug}...")
            try:
                result = self.tu.tools.drugbank_get_pharmacology_by_drug_name_or_drugbank_id(
                    query=drug,
                    case_sensitive=False,
                    exact_match=False,
                    limit=1
                )

                if result.get('data', {}).get('drugs'):
                    pharm = result['data']['drugs'][0]
                    pharmacology[drug] = {
                        'mechanism': pharm.get('mechanism_of_action', 'N/A')[:200],
                        'absorption': pharm.get('absorption', 'N/A')[:100]
                    }
                    print(f"   ✅ Retrieved")
            except Exception as e:
                print(f"   ⚠️ Error: {e}")
                pharmacology[drug] = {'mechanism': 'Not available', 'absorption': 'Not available'}

        return pharmacology

    def _search_fda_labels(self, drug_a, drug_b):
        """Search FDA labels via DailyMed."""
        print("\n4️⃣ FDA Label Search (DailyMed)")
        labels = []

        for drug in [drug_a, drug_b]:
            print(f"   Searching labels for {drug}...")
            try:
                # Search for SPLs
                result = self.tu.tools.DailyMed_search_spls(query=drug)

                if result.get('data', {}).get('spls'):
                    spls = result['data']['spls']
                    if spls:
                        spl = spls[0]
                        labels.append({
                            'drug': drug,
                            'setid': spl.get('setid', 'N/A'),
                            'title': spl.get('title', 'N/A')
                        })
                        print(f"   ✅ Found label: {spl.get('title', 'N/A')[:50]}...")
            except Exception as e:
                print(f"   ⚠️ Error: {e}")

        return labels

    def _search_literature(self, drug_a, drug_b):
        """Search PubMed for interaction literature."""
        print("\n5️⃣ Literature Search (PubMed)")
        literature = {}

        query = f'("{drug_a}"[Title/Abstract] AND "{drug_b}"[Title/Abstract] AND "drug interaction"[Title/Abstract])'
        print(f"   Query: {query}")

        try:
            result = self.tu.tools.PubMed_search_articles(
                query=query,
                max_results=10
            )

            if result.get('data', {}).get('articles'):
                articles = result['data']['articles']
                literature['count'] = len(articles)
                literature['top_articles'] = [
                    {
                        'title': art.get('title', 'N/A')[:100],
                        'pmid': art.get('pmid', 'N/A')
                    }
                    for art in articles[:3]
                ]
                print(f"   ✅ Found {len(articles)} articles")
            else:
                literature['count'] = 0
                print(f"   ℹ️ No articles found")
        except Exception as e:
            print(f"   ⚠️ Error: {e}")
            literature['count'] = 0

        return literature

    def _query_adverse_events(self, drug_a, drug_b):
        """Query FAERS for adverse events."""
        print("\n6️⃣ Adverse Events (FAERS)")
        adverse_events = {}

        for drug in [drug_a, drug_b]:
            print(f"   Querying FAERS for {drug}...")
            try:
                result = self.tu.tools.FAERS_count_reactions_by_drug_event(
                    medicinalproduct=drug,
                    event_name="drug interaction"
                )

                if result.get('data'):
                    count = result['data'].get('count', 0)
                    adverse_events[drug] = count
                    print(f"   ✅ Found {count} reports")
            except Exception as e:
                print(f"   ⚠️ Error: {e}")
                adverse_events[drug] = 0

        return adverse_events

    def _calculate_risk(self, report):
        """Calculate DDI risk score (0-100)."""
        print("\n7️⃣ Risk Scoring")
        score = 0

        # Mechanisms found: +40 points
        if any('No documented' not in m.get('description', '') for m in report['mechanisms']):
            score += 40
            print(f"   ✅ Mechanisms identified: +40")

        # FDA labels found: +20 points
        if len(report['fda_labels']) >= 2:
            score += 20
            print(f"   ✅ FDA labels found: +20")

        # Literature evidence: +20 points
        lit_count = report.get('clinical_evidence', {}).get('count', 0)
        if lit_count > 0:
            score += 20
            print(f"   ✅ Literature evidence: +20")

        # FAERS reports: +20 points
        faers_total = sum(report.get('clinical_evidence', {}).values())
        if faers_total > 100:
            score += 20
            print(f"   ✅ FAERS reports ({faers_total}): +20")

        # Determine severity
        if score >= 70:
            severity = "MAJOR"
        elif score >= 40:
            severity = "MODERATE"
        else:
            severity = "MINOR"

        print(f"   📊 Total Score: {score}/100 ({severity})")

        return score, severity

    def _generate_recommendations(self, report):
        """Generate clinical management recommendations."""
        print("\n8️⃣ Management Recommendations")
        recommendations = []

        severity = report['severity']

        if severity == "MAJOR":
            recommendations.append("⚠️ AVOID COMBINATION - Consider alternative drugs")
            recommendations.append("If combination unavoidable, close monitoring required")
            recommendations.append("Dose adjustment may be necessary")
        elif severity == "MODERATE":
            recommendations.append("✓ Combination may be used with monitoring")
            recommendations.append("Watch for signs of interaction")
            recommendations.append("Consider dose adjustment if needed")
        else:
            recommendations.append("✓ Low risk - routine monitoring sufficient")
            recommendations.append("No special precautions required")

        # Add mechanism-specific recommendations
        for mech in report['mechanisms']:
            if 'CYP' in mech.get('description', ''):
                recommendations.append("Monitor for CYP-mediated interactions")

        print(f"   ✅ Generated {len(recommendations)} recommendations")

        return recommendations


def main():
    """Run DDI analysis examples."""
    print("=" * 80)
    print("DRUG-DRUG INTERACTION PIPELINE - FIXED VERSION")
    print("Using ToolUniverse's 1,264 tools")
    print("=" * 80)
    print()

    analyzer = DDIAnalyzer()

    # Example 1: Warfarin + Antibiotic
    print("\n" + "=" * 80)
    print("EXAMPLE 1: Warfarin + Amoxicillin")
    print("=" * 80)
    _ = analyzer.analyze("warfarin", "amoxicillin")

    # Example 2: Statin + Azole
    print("\n\n" + "=" * 80)
    print("EXAMPLE 2: Simvastatin + Ketoconazole")
    print("=" * 80)
    _ = analyzer.analyze("simvastatin", "ketoconazole")

    print("\n" + "=" * 80)
    print("✅ PIPELINE COMPLETE")
    print("=" * 80)
    print(f"\n📄 Reports generated:")
    print(f"   - DDI_report_warfarin_amoxicillin.md")
    print(f"   - DDI_report_simvastatin_ketoconazole.md")
    print(f"\n💡 DDI skill is now functional with correct tool usage!")


if __name__ == "__main__":
    main()
