model:
  name: "KNO1D"
  channels: 32
  modes: 64
  depths: 4
  resolution: 1024

data:
  name: "burgers1d"
  path: "./dataset"
  in_channels: 1
  out_channels: 1
  train_size: 1000
  test_size: 200
  batch_size: 8
  sub: 32

optimizer:
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001

summary_dir: "./summary_dir/"
eval_interval: 10
