params:
  model_name: 'ICNet'
  case: 'Single Klein-Gordon equation'
  data_name: 'Single-Klein-Gordon.mat'
  second_path: 'pretrain'
  device: 'GPU'
  init_steps: 50
  stop_steps: 230
  time_steps: 50
  device_id: 3
  load_params: 'True'
  second_path1: 'pretrain'
  network_size: [3, 30, 30, 30, 30, 30, 30, 30, 30, 1]
  description_SKG: ['u_xx','u_yy','1','u','u**2', 'u**3']
  learning_rate: [0.001, 0.0005, 1.0e-04, 1.0e-05]
  epochs: [3e5, 3e5, 1e4, 1e4]
  BatchNo: 1
  lam: 1e-5
  d_tol: 1.0
  
