params:
  model_name: 'ICNet'
  data_name: 'KS.mat'
  init_steps: 0
  stop_steps: 150
  time_steps: 50
  case: 'Kuramoto-Sivashinsky equation'
  device: 'GPU'
  device_id: 3
  load_params: 'True'
  second_path: 'pretrain'
  network_size: [2, 40, 40, 40, 40, 40, 40, 40, 40, 1]
  description_ks: ['uu_x','1','u_x','u_xx', 'u_xxx','u_xxxx']
  learning_rate: [0.001, 0.0005, 1.0e-04, 1.0e-05]
  epochs: [3e5, 3e5, 1e4, 1e4]
  BatchNo: 1
  lam: 1e-5
  d_tol: 1.0
  
