params:
  model_name: 'ICNet'
  case: 'Two-dimensional Burgers equation'
  data_name: 'Burgers2D.mat'
  second_path: 'pretrain'
  device: 'GPU'
  init_steps: 30
  stop_steps: 150
  time_steps: 40
  device_id: 3
  load_params: 'True'
  network_size: [3, 60, 60, 60, 60, 60, 60, 60, 60, 2] 
  description_burgers_u: ['uu_x','vu_y','1','u_x', 'u_xx', 'u_y', 'u_yy', 'u_xy', 'v_x', 'v_xx', 'v_y', 'v_yy', 'v_xy']
  description_burgers_v: ['uv_x','vv_y','1','u_x', 'u_xx', 'u_y', 'u_yy', 'u_xy', 'v_x', 'v_xx', 'v_y', 'v_yy', 'v_xy']
  learning_rate: [0.001, 0.0005, 1.0e-04, 1.0e-05]
  epochs: [3e5, 3e5, 1e4, 1e4]
  BatchNo: 1
  lam: 10**-5
  d_tol: 5.0
  second_path1: 'pretrain'
  
