model:
  in_channels: 2
  out_channels: 1
  resolution: 128
  load_ckpt: False
  unet2d:
    kernel_size: 2
    stride: 2
    base_channels: 64

data:
  root_dir: "./dataset/"
  dataset_name: "S_0_0_10_5_10_5_5.npz"
  data_size: 3600
  train_size: 3000
  means: [0.5803, 0.0401, 0.6564]
  stds: [0.3523, 0.0885, 0.1459]
  T_in: 8
  T_out: 32
  train_batch_size: 8
  test_batch_size: 8

optimizer:
  epochs: 2000
  save_epoch: 100
  warm_up_epochs: 1
  gamma: 0.2
  weight_decay: 0.001
  amp_level:
    unet2d: "O1"
  lr:
    unet2d: 0.0001

summary:
  summary_dir: "./summary_dir/"
  pretrained_ckpt_dir: "./summary_dir/ckpt"
  save_ckpt_interval: 10
  test_interval: 10

variation:
  max_scale: 200
  loss1_scale: 100
  hatch_extent: 3