hidden_dim: 256
latent_dim: 256
fc_num_layers: 0
max_atoms: 20
cost_natom: 1.
cost_coord: 10.
cost_type: 1.
cost_lattice: 10.
cost_composition: 1.
cost_edge: 10.
cost_property: 1.
beta: 0.01
max_neighbors: 20
radius: 7.
sigma_begin: 10.
sigma_end: 0.01
type_sigma_begin: 5.
type_sigma_end: 0.01
num_noise_level: 50
teacher_forcing_lattice: True
predict_property: True

Encoder:
  hidden_channels: 128
  num_blocks: 4
  int_emb_size: 64
  basis_emb_size: 8
  out_emb_channels: 256
  num_spherical: 7
  num_radial: 6
  cutoff: 7.0
  max_num_neighbors: 20
  envelope_exponent: 5
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3

Decoder:
  hidden_dim: 128

Optimizer:
  learning_rate: 0.001
  factor: 0.6
  patience: 30
  cooldown: 10
  min_lr: 0.0001

Scaler:
    TripInteraction_1_had_rbf: 18.873615264892578
    TripInteraction_1_sum_cbf: 7.996850490570068
    AtomUpdate_1_sum: 1.220463752746582
    TripInteraction_2_had_rbf: 16.10817527770996
    TripInteraction_2_sum_cbf: 7.614634037017822
    AtomUpdate_2_sum: 0.9690994620323181
    TripInteraction_3_had_rbf: 15.01930046081543
    TripInteraction_3_sum_cbf: 7.025179862976074
    AtomUpdate_3_sum: 0.8903237581253052
    OutBlock_0_sum: 1.6437848806381226
    OutBlock_0_had: 16.161039352416992
    OutBlock_1_sum: 1.1077653169631958
    OutBlock_1_had: 13.54678726196289
    OutBlock_2_sum: 0.9477927684783936
    OutBlock_2_had: 12.754337310791016
    OutBlock_3_sum: 0.9059251546859741
    OutBlock_3_had: 13.484951972961426
