model: 
  hidden_dim: 1000
  hidden_dropout: 0.0
  n_heads: 10
  n_pga_targets: 15
  output_location_dims: [150,100,50,30,3]
  output_mlp_dims: [150,100,50,30,1]
  transformer_layers: 6
  waveform_model_dims: [500,500,500]
  wavelength: [[0.01,15],[0.01,15],[0.01,10]]
  times: [5]
  run_with_less_data: false
  pga: true
  mode: test
  no_event_token : False
data:
  root_dir: "./dataset"
  batch_size: 64
  max_stations: 5
  disable_station_foreshadowing: true
  key: Mag
  magnitude_resampling: 1
  min_mag: None
  min_upsample_magnitude: 4
  aug_large: True
  pga_from_inactive: true
  pga_key: pga
  pga_selection_skew: 1000
  pos_offset: [30,102]
  scale_metadata: false
  selection_skew: 1000
  shuffle_train_dev: true
  transform_target_only: false
  trigger_based: true
  waveform_shape: [3000, 3]
  overwrite_sampling_rate: None
  noise_seconds: 5
summary:
  summary_dir: "./summary"
  ckpt_path: "./dataset/ckpt/g_team.ckpt"
