data:
  root_dir: 'dataset/'
  batch_size: 128
  n_channel_p: 3  # Cp = (None, 128, 128, 3)
  n_channel_u: 2  # u = (None, 128, 128, 2) including u and v
  latent_z_n_channel: 50  # z = (None, 8, 8, 50)
  column_names: ['u_r10_train', 'u_r5_train', 'u_r3_train', 'u_r1_train', 'cp_fluc_train', 'Re_c_train', 'scaling_input_train']

critic:
  lambda_GP: 10
  critic_model_lr: 0.00025
  n_critic: 3

generator:
  lambda_L2_u: 1000
  lambda_L2_gradu: 100
  gan_model_lr: 0.004

summary:
  dxy: [0.0242, 0.0291]
  plot_n: 5
  n_imgs: 128
  merge_n_imgs: 8
  epochs: 350
  sample_interval: 10