model_name: inversion_net
case: flatvel_a
anno_path: ./data
train_anno: flatvel_a_train_mini.txt
val_anno: flatvel_a_val_mini.txt
file_size: 0
device_target: GPU
device_num: 0
mode: 0
amp_level: O0
dims: [ 32, 64, 128, 256, 512 ]
sample_spatial: 1.0
sample_temporal: 1
lambda_g1v: 1.0
lambda_g2v: 1.0
batch_size: 128
lr: 0.0001
lr_milestones: [100, 200]
momentum: 0.9
weight_decay: 0.0001
lr_gamma: 0.1
lr_warmup_epochs: 0
start_epoch: 0
epoch_block: 40
num_block: 3
workers: 8
k: 1
print_freq: 50
save_fig: true
vis_path: figures
vis_batch: 2
vis_sample: 3
missing: 0
std: 0
save_ckpt: true
load_ckpt: false
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/inversion_net_O0.ckpt
figures_path: ./figures
log_path: ./logs
download_data: inversion_net
force_download: false
