model:
  name: FNO1D
  in_channels: 1
  out_channels: 1
  modes: 16
  resolutions: 1024
  hidden_channels: 64
  depths: 4
data:
  name: "burgers1d"
  root_dir: "./dataset"
  train:
    num_samples: 1000
  test:
    num_samples: 200
  batch_size: 8
  resolution: 1024
  t_in: 1
  t_out: 1
  step: 8
optimizer:
  learning_rate: 0.001
  epochs: 100
summary:
  test_interval: 10
  summary_dir: "./summary"
  ckpt_dir: "./checkpoints"