model_type: spno
spno:
    pred_model_name: unet
    super_model_name: fno
    in_channels: 10
    patch_num: 4
unet:
    in_channels: 10
    out_channels: 1
    channels: 20
fno:
    in_channels: 2
    out_channels: 1
    resolution:
        - 32
        - 32
    modes: 12
    channels: 20
    depths: 3
data:
    path: ./data
    num_samples:
        train: 500
        test: 100
train:
    batch_size: 32
    hole_num_set: [1,2,3,5]
    lr_init: 1.e-4
    epochs: 300
    optimizer: AdamW
    weight_decay: 0.0
    lr_scheduler:
        enable_warmup: True
        warmup_epochs: 10
test:
    batch_size: 32
    hole_num_set: [1,2,3,5,10]
    interval: 25
record_path: ./exp
