model_name: phygeonet
description: phygeonet
case: phygeonet
save_ckpt: true
load_ckpt: false
save_fig: true
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/model_final.ckpt
log_path: ./logs
figures_path: ./figures
load_data_path: ./data/case0
save_data_path: ./data/case0
lr: 0.001
epochs: 1501
batch_size: 1
download_data: phygeonet
force_download: false
amp_level: O0
mode: 0
