data:
  data_path: "dataset/periodic_hill_20230727.dat"
  batch_size: 4002
model:
  in_channels: 2
  out_channels: 6
  activation: "tanh"
  layers: 10
  neurons: 128
  residual: false
optimizer:
  initial_lr: 0.001
  weight_decay: 0.0

train_epochs: 10000
eval_interval_epochs: 5
ckpt_path: "./summary/ckpt"
summary_dir: "./summary"
visual_dir: "./prediction_result"
save_checkpoint_epochs: 50
keep_checkpoint_max: 10
load_ckpt: false
load_ckpt_path: "./summary/ckpt/rans_1000.ckpt"
