model_name: pinn_elastodynamics
description: pinn elastodynamics
case: elastic_wave_confined
uv_layers: [3, 140, 140, 140, 140, 140, 140, 7]
save_ckpt: true
save_fig: true
load_ckpt: false
save_ckpt_path: ./checkpoints
load_data_path: ./data
load_ckpt_path: ./checkpoints/uv_NN_14s_float32_new.pickle
figures_path: ./figures/output
log_path: ./logs
print_interval: 100
ckpt_interval: 1000
lr: 0.001
epochs: 100000
use_lbfgs: false
max_iter_lbfgs: null
download_data: pinn_elastodynamics
force_download: false
amp_level: O3
mode: 0
