cae_data:
  data_path: "./dataset/kh.npy"
  batch_size: 32
  time_size: 1786      # The numbers of the snapshots
cae_optimizer:
  lr: 0.001
  weight_decay: 0.000001
  epochs: 4400
  save_ckpt_interval: 400
  summary_dir: "./summary"      # The directory where the training process files are saved
cae_model:
  data_dimension: [256, 128, 64, 32, 16, 8]
  conv_kernel_size: 3
  maxpool_kernel_size: 2
  maxpool_stride: 2
  encoder_channels: [1, 40, 30, 20, 10, 5, 1]
  decoder_channels: [1, 1, 5, 10, 20, 30, 40, 1]
  channels_dense: [16, 30, 25, 20]
  latent_size: 20
lstm_data:
  batch_size: 32
  time_size: 1786
  latent_size: 20
  time_window: 200
  gaussian_filter_sigma: 3
lstm_optimizer:
  lr: 0.001
  weight_decay: 0.000001
  epochs: 4400
  save_ckpt_interval: 400
  summary_dir: "./summary"
lstm_model:
  latent_size: 20      # The input size of LSTM
  hidden_size: 200
  num_layers: 3
prediction:
  encoder_data_split: 4                                  # Split the dataset to reduce memory
  encoder_time_spilt: [0, 500, 1000, 1500, 1786]
  decoder_data_split: 4
  decoder_time_spilt: [0, 500, 1000, 1500, 1786]
  cae_ckpt_path: "./summary/ckpt/cae_4400.ckpt"
  lstm_ckpt_path: "./summary/ckpt/lstm_4400.ckpt"
  prediction_result_dir: "./prediction_result"
