rectangle: # whole solution region
    coord_min: [0., 0.]
    coord_max: [3.141592653589793, 3.141592653589793] # [pi, pi]
rectangle_src: # source region
    coord_min: [1.5307963267948965, 1.5307963267948965] # [pi/2 - 0.04, pi/2 - 0.04]
    coord_max: [1.6107963267948966, 1.6107963267948966] # [pi/2 + 0.04, pi/2 + 0.04]
data:
    domain:
        random_sampling: True
        size: 1000000
        # sampler: "uniform"
        sampler: "lhs"
    BC:
        random_sampling: True
        size: 1000000
        # sampler: "uniform"
        sampler: "lhs"
batch_size: 5000
optimizer:
    initial_lr: 1.0e-3
model:
  in_channels: 2
  out_channels: 1
  layers: 5
  neurons: 128
  num_scales: 2
  activation: "sin"
keep_checkpoint_max: 2
