model:
  name: "KNO2D"
  channels: 20  # alternative 32, 20
  modes: 16  # alternative 24, 12
  depths: 4
  resolution: 64

data:
  name: "navier_stoke_2d"
  path: "./dataset"
  in_channels: 1
  out_channels: 1
  train_size: 19000
  test_size: 3800
  batch_size: 19
  sub: 2

optimizer:
  epochs: 50
  lr: 0.001
  weight_decay: 0.0001

summary_dir: "./summary_dir/"
eval_interval: 10
