model_name: hfm
description: HFMNet
case: Cylinder2D_flower_systematic
layers: [3, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 4]
save_ckpt: true
load_ckpt: false
save_result: true
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/model_iter_300000_float32.ckpt
load_data_path: ./data
save_data_path: ./data
log_path: ./logs
print_interval: 10
lr: 0.001
t: 1500
n: 1500
total_time: 40
epochs: 500001
batch_size: 1000
download_data: hfm
force_download: false
amp_level: O0
mode: 0
