data:
  data_path: './dataset/Burgers_2001x2x100x100_[dt=00025].mat'
  pattern: 'data_driven'
  dx: 0.01
  dy: 0.01
  dt: 0.00025
  nu: 0.005
  rollout_steps: 40
  extrapolations: 1800
model:
  in_channel: 2
  upscaler_hidden_channel: 8
  rcnn_hidden_channel: 8
  out_channels: 2
  kernel_size: 5
  stride: 2
optimizer:
  pretrain:
    epochs: 6000
    name_conf: "Adam"
    learning_rate: 0.001
  finetune:
    learning_rate: 2e-3
    gamma: 0.96
    milestone_num: 150
    epochs: 15000
    name_conf: "Adam"
summary:
  ckpt_dir: './checkpoints'
  fig_save_path: "./figures/data_driven"
  ckpt_file_name: "./model/checkpointtrain.ckpt"