name: "pde_net"
eval_interval: 10
lr_scheduler_gamma: 0.5
lr: 0.001
save_epoch_interval: 50
mesh_size: 50
solver_mesh_scale: 5
enable_noise: True
start_noise_level: 0.015
end_noise_level: 0.015
variant_coe_magnitude: 1.0
init_freq: 4
batch_size: 16
epochs: 500
multi_step: 20
learning_rate_reduce_times: 4
dt: 0.015
kernel_size: 5
max_order: 4
channels: 1
perodic_padding: True
if_frozen: False
enable_moment: True
summary_dir: "./summary_dir/summary"
mindrecord_data_dir: "./data"
figure_out_dir: "figure"