dataset:
  data_name: 'mp_20'
  train:
    path: './dataset/mp_20/train.csv'
    save_path: './dataset/mp_20/train.npy'
  val:
    path: './dataset/mp_20/val.csv'
    save_path: './dataset/mp_20/val.npy'
  test:
    path: './dataset/mp_20/test.csv'
    save_path: './dataset/mp_20/test.npy'

model:
  # For dataset carbon, mp, mpts
  hidden_dim: 512
  num_layers: 6
  num_freqs: 128
  # # For dataset perov
  # hidden_dim: 256
  # num_layers: 4
  # num_freqs: 10

train:
  ckpt_dir: "./ckpt/mp_20"
  # 3500, 4000, 1000, 1000 epochs for Perov-5, Carbon-24, MP-20 and MPTS-52 respectively.
  epoch_size: 1000
  # 512, 512, 128, 128 for Perov-5, Carbon-24, MP-20 and MPTS-52 respectively.
  batch_size: 256
  seed: 1234

checkpoint:
  last_path: "./ckpt/mp_20/last_test.ckpt"

test:
  # 1024 for perov, 512 for carbon and mp, 256 for mpts
  batch_size: 512
  num_eval: 1
  # 1e-5 for mp and mpts, 5e-7 for perov, 5e-6 for carbon num_eval=1 and 5e-7 for carbon num_eval=20
  step_lr: 1e-5
  eval_save_path: './ckpt/mp_20/predict_crys.pkl'
  metric_dir: './ckpt/mp_20/'








