mode: eval
task_name: "hhblits"  # "hhblits" or "deeploc"
t5_config_path: "prot_t5_xl_uniref50_ms"  # T5 base模型; 包含yaml，ckpt，tokenizor model的目录
checkpoint_path: "./model_deeploc_loc.ckpt"  # 下游任务的ckpt； 未开源需要自己训练

train:
  lr: 0.001
  epochs: 4
  batch_size: 16
  train_data_path: ""  # 预测时为空
  eval_data_path: ""
  checkpoint_save_path: null
  cate_name: ''