mode: "train"
parallel: False   # 是否使用并行
t5_config_path: "prot_t5_xl_uniref50_ms/t5_xl.yaml"    # T5 yaml配置文件
load_model_path: null    # 可以配置checkpoint ckpt路径；用于继续训练

# 训练相关参数
train:
  train_data_path: 'train_data'  # 训练文件目录；训练文件为mindrecord格式
  lr: 2.0e-5  # learning rate
  warmup_steps: 0 
  batch_size: 32
  epochs: 1
  save_steps: 20000
  save_ckpt_path: "output/"
  use_clip_grad: True
  max_grad_norm: 1