model:
  name: koopman_vit
  backbone: "ViTKNO"
  encoder_depth: 16
  encoder_network: False
  encoder_embed_dim: 768
  num_blocks: 16
  mlp_ratio: 4
  dropout_rate: 1.
  distribute: False
  amp_level: 'O2'
data:
  name: "era5"
  root_dir: "./dataset"
  feature_dims: 69
  pressure_level_num: 13
  patch: True
  patch_size: 8
  batch_size: 1
  h_size: 128
  w_size: 256
  t_in: 1
  t_out_train: 1
  t_out_valid: 20
  t_out_test: 20
  valid_interval: 1
  test_interval: 1
  train_interval: 1
  pred_lead_time: 6
  data_frequency: 6
  train_period: [2015, 2015]
  valid_period: [2016, 2016]
  test_period: [2017, 2017]
  grid_resolution: 1.4
  num_workers: 1
optimizer:
  name: "adam"
  weight_decay: 0.0
  epochs: 10
  finetune_epochs: 1
  warmup_epochs: 1
  initial_lr: 0.0001
summary:
  save_checkpoint_steps: 20
  keep_checkpoint_max: 10
  plt_key_info: True
  key_info_timestep: [ 6, 72, 120 ]
  valid_frequency: 10
  summary_dir: './summary'
train:
  name: "oop"
  data_sink: True
