data:
  root_dir: 'dataset'
  velocity_field: 'velocity.npy'
  velocity_dx: 16.          # grid interval of the velocity matrix
  source_wave: 'srcwaves.csv'
  source_locations: 'srclocs.csv'

solve:
  dt: 0.02                  # time interval of the output
  nt: 300                   # number of time points of the output, must be even (required by rfft)
  downsample_mode: 'linear' # way to downsample the frequency points, options: linear, exp, square
  downsample_rate: 1        # only 1/downsample_rate frequency points will be solved
  n_batches: 4              # the number of batches for frequencies to be diveded into

summary:
  root_dir: 'results'
