model:
  root_dir: "./"
  name: SNO2D
  in_channels: 1
  out_channels: 1
  hidden_channels: 64
  kernel_size: 5
  modes: 15
  resolution: 64
  sno_layers: 3
  usno_layers: 1
  unet_strides: 2
data:
  name: "navier_stokes_2d"
  root_dir: "./dataset"
  train_size: 19000
  test_size: 3800
  batch_size: 19
  resolution: 64
  poly_type: "Legendre"
optimizer:
  learning_rate: 0.0005
  epochs: 90
  weight_decay: 0.001
  warmup_epochs: 1
  grad_clip_norm: 1.
summary:
  root_dir: "./summary"
  ckpt_dir: "./checkpoints"
  test_interval: 10
  save_ckpt_interval: 30