model_name: pinns_swe
description: pinns_swe
case: pinns_swe
layers: [4, 20, 20, 20, 20, 1]
load_ckpt: false
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/model4_float32.ckpt
save_fig: true
figures_path: ./figures
log_path: ./logs
lr: 0.001
epochs: 18000
n_pde: 100000
n_iv: 10000
u: 1
h: 1000
days: 12
download_data: pinns_swe
force_download: false
amp_level: O3
mode: 0
