params:
  grid_type: 'structure'
  activ_fun: 'swish'
  device_target: 'CPU'
  device_id: 0
  mode: 'PYNATIVE'
  nx: 512
  ny: 512
  in_channels: 1
  out_channels: 1
  batch_size: 5
  lambda_p: 1
  lambda_eq: 1
  weight_decay: 0.000001
  
  
  
  
