model_name: enso
description: Multi_year_enso
case: exp2_pretrain
save_ckpt: true
load_ckpt: false
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/exp2_aftertrain/enso_float16.ckpt
save_data: true
load_data_path: ./data
save_data_path: ./data
save_figure: true
figures_path: ./figures
print_interval: 10
ckpt_interval: 10
log_path: ./logs
lr: 0.01
epochs: 20
batch_size: 400
skip_aftertrain: false
epochs_after: 5
batch_size_after: 30
lr_after: 1.0e-06
download_data: enso
force_download: false
amp_level: O3
mode: 0
