cae_data:
  data_path: "./dataset/riemann.npy"
  batch_size: 16
  time_size: 1250      # The numbers of the snapshots
cae_optimizer:
  lr: 0.001
  weight_decay: 0.000001
  epochs: 4400
  save_ckpt_interval: 400
  summary_dir: "./summary"      # The directory where the training process files are saved
cae_model:
  data_dimension: [128, 64, 32, 16, 8, 4]
  conv_kernel_size: 3
  maxpool_kernel_size: 2
  maxpool_stride: 2
  encoder_channels: [1, 30, 25, 20, 15, 10, 5]
  decoder_channels: [5, 5, 10, 15, 20, 25, 30, 1]
  channels_dense: [20, 30, 25, 20]
  latent_size: 20
lstm_data:
  batch_size: 32
  time_size: 1250
  latent_size: 20
  time_window: 150
  gaussian_filter_sigma: 3
lstm_optimizer:
  lr: 0.001
  weight_decay: 0.000001
  epochs: 4400
  save_ckpt_interval: 400
  summary_dir: "./summary"
lstm_model:
  latent_size: 20      # The input size of LSTM
  hidden_size: 200
  num_layers: 3
prediction:
  encoder_data_split: 1                         # Split the dataset to reduce memory
  encoder_time_spilt: [0, 1250]
  decoder_data_split: 1
  decoder_time_spilt: [0, 1250]
  cae_ckpt_path: "./summary/ckpt/cae_4400.ckpt"
  lstm_ckpt_path: "./summary/ckpt/lstm_4400.ckpt"
  prediction_result_dir: "./prediction_result"
