data:
  data_path: "./data/"                # sata storage path relative to train.py
  train_radio: 0.75                   # Proportion of training set
  eval_radio: 0.1                     # Proportion of training set
  skip: 1                             # The time sampling interval of the data
  t_in: 1                             # The number of time steps for the snapshot at the input
  t_out: 1                            # The number of time steps for output snapshots
model:
  in_dims: 4                          # The number of channels of the flow snapshot as input
  out_dims: 4                         # The number of channels of the flow snapshot as output
  base: 64                            # The number of channels for the first layer to extract features
  batch_size: 10                      # Initialization method of neural network weights
  loss_fn: "GradientRRMSE"            # Class selection for loss functions
  metric_fn: "RRMSE"                  # Class selection for metric functions
  loss_weight: 100.0                  # Artificially specified gradient loss weights
  dynamic_flag: True                  # Dynamic adjustment strategy
optimizer:
  train_epochs: 500                   # total number of training epochs
  initial_lr: 0.001                    # Initial learning rate
  warmup_epochs: 50                   # The number of steps required to warm up the learning rate
summary:
  eval_interval: 10                   # Evaluate the model every certain number of training epochs
  summary_dir: "./summary/"           # The directory where the training process files are saved
  epoch_load: 500                     # The model parameter (ckpt) number to be read
