# Copyright 2024 DeepMind Technologies Limited
#
# AlphaFold 3 source code is licensed under CC BY-NC-SA 4.0. To view a copy of
# this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# To request access to the AlphaFold 3 model parameters, follow the process set
# out at https://github.com/google-deepmind/alphafold3. You may only use these
# if received directly from Google. Use is subject to terms of use available at
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

class FastaFileIterator:
    def __init__(self, fasta_path: str) -> None: ...
    def __iter__(self) -> FastaFileIterator: ...
    def __next__(self) -> tuple[str,str]: ...

class FastaStringIterator:
    def __init__(self, fasta_string: str | bytes) -> None: ...
    def __iter__(self) -> FastaStringIterator: ...
    def __next__(self) -> tuple[str,str]: ...

def parse_fasta(fasta_string: str | bytes) -> list[str]: ...
def parse_fasta_include_descriptions(fasta_string: str | bytes) -> tuple[list[str],list[str]]: ...
