model_name: mgnet
description: mgnet
case: mgnet
dataset: cifar100
save_ckpt: true
load_ckpt: false
save_ckpt_path: ./checkpoints
load_ckpt_path: ./checkpoints/model_300.ckpt
load_data_path: ./data/cifar-100-binary
log_path: ./logs
print_interval: 10
ckpt_interval: 2000
num_ite: [2, 2, 2, 2]
num_channel_u: 256
num_channel_f: 256
wise_b: true
batch_size: 128
epochs: 300
lr: 0.1
download_data: mgnet
force_download: false
amp_level: O3
mode: 0
