#Control Sequence
data_path: './config/T4_Train_DOS'
output_path: './results'
train_e: False #False #True
ert_epochs: 50
ert_batch_size: 10
ert_patience: 10
train_dos: True #False #True
drt_epochs: 50
drt_batch_size: 10
drt_patience: 10
new_weights_e: False #False #True
new_weights_dos: False #False #True
test_chg: True #False #True
test_e: True #False #True
test_dos: True #False #True

#Fingerprinting specific
fp_file:  'fp'
cut_off_rad: 5.0
batch_size_fp: 10000
widest_gaussian: 6
narrowest_gaussian: 0.5
num_gamma: 18

#For plotting
plot_dos: True
tot_chg: False
comp_chg: False
write_chg: True
ref_chg: False
grid_spacing: 0.7