data:
  data_path: "./dataset/2D_cylinder_flow.npy"
  pred_len: 1
  seq_len: 12
  label_len: 12
  padding: 0
  batch_size: 32
  time_size: 401
  latent_size: 20
  input_dim: 256
  train_ratio: 0.8

optimizer:
  lr: 0.05
  weight_decay: 0.01
  epochs: 30
  save_ckpt_interval: 10
  eval_interval: 10
  summary_dir: "./summary"

cae_transformer:
  enc_in: 20 
  dec_in: 20
  c_out: 20
  pred_len: 1
  label_len: 12
  data_dimension: [256, 128, 64, 32, 16, 8]
  conv_kernel: 3
  maxpool_kernel: 2
  maxpool_stride: 2
  channels_encoder: [1, 30, 25, 20, 10, 5, 1]
  channels_decoder: [1, 1, 5, 10, 20, 25, 30, 1]
  channels_dense: [16, 30, 25, 20]
  
prediction:
  encoder_data_split: 4                                  # Split the dataset to reduce memory
  encoder_time_spilt: [0, 500, 1000, 1500, 1785]
  decoder_data_split: 4
  decoder_time_spilt: [0, 500, 1000, 1500, 1785]
  model_ckpt_path: "./summary/ckpt/model_30.ckpt"
  prediction_result_dir: "./prediction_result"
