params:
  model_name: 'NSFNet'
  case: 'Kovasznay-Flow'
  device: 'GPU'
  device_id: '2'
  load_params: False
  load_params_test: True
  second_path1: 'train'
  network_size: [2, 50, 50, 50, 50, 3]
  learning_rate: [1.0e-03, 1.0e-04, 1.0e-05, 1.0e-06]
  epochs: [5e3, 5e3, 5e4, 5e4]
  re: 40