model:
  work_space: "./"
  name: FNO2D_time
  in_channels: 1
  out_channels: 1
  input_resolution: 64
  modes: 12
  width: 20
  depth: 4
data:
  name: "navier_stoke_2d"
  path: "./dataset"
  train_size: 19000
  test_size: 3800
  batch_size: 19
  resolution: 64
  sub: 2
optimizer:
  initial_lr: 0.001
  warmup_epochs: 1
  train_epochs: 150
  weight_decay: 0.001

summary_dir: "./summary"
eval_interval: 10
save_ckpt_interval: 50
test_batch_size: 1
